//
//  StudentLocation.swift
//  OnTheMap
//
//  Created by Fatimah on 09/03/1441 AH.
//  Copyright © 1441 Fatimah. All rights reserved.
//

import Foundation

struct StudentLocation: Codable {
    var objectId: String // an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
    let uniqueKey: String // you should populate this value using your Udacity account id
    let firstName: String
    let lastName: String
    let mapString: String
    let mediaURL: String
    let latitude: Double
    let longitude: Double
}
